---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:

    - name: "install python for Ansible."
      # Your code here
      become: true
      raw: test -e /usr/bin/python3 || (apt update -y && apt install python3 -y)
      changed_when: false

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    # Add more env vars here
      NODE_ENV=local
      VERSION=1
      TYPEORM_CONNECTION=postgres
      TYPEORM_MIGRATIONS_DIR=./src/migrations
      TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
      TYPEORM_MIGRATIONS=./src/migrations/*.ts
      TYPEORM_HOST=localhost
      TYPEORM_PORT=5532
      TYPEORM_USERNAME=postgres
      TYPEORM_PASSWORD=password
      TYPEORM_DATABASE=glee


  roles:
    # Your code here
    - configure-prometheus-node-exporter
    - configure-server1
