---
- name: "upgrade packages."
  become_user: root
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become_user: root
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become_user: root
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present